spring.application.name=employeeEntity

#
# JDBC properties
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee
#spring.datasource.username=postgres
#spring.datasource.password=#Musa5254

spring.data.mongodb.uri=ENC(xsUZt5OxphOo+rBymGJOeg/8rxdCE3za98PuJg9n4PWOWhhMGEI2LDvMPaJtD3SoRmZ2h5m2y91AmfTTwgrp4TBjuVpBEgapm0UQz7dwLQ479c2NRW/5s9Bskje2HIUD2Xv75IW/tsuYae/ja3P0Yg==)

logging.level.org.mongodb.driver.protocol.command=DEBUG

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG










