spring.application.name=employeeEntity

#
# JDBC properties
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee
#spring.datasource.username=postgres
#spring.datasource.password=#Musa5254

spring.data.mongodb.uri=mongodb://musaisah455:%23Musa5254@localhost:27017/employee?authSource=admin

logging.level.org.mongodb.driver.protocol.command=DEBUG

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG










